### ISSUE TITLE
ubuntu ppa  for 12.04+

### ISSUE THREAD

**Issue by lyc256** [persmule/amule-dlp#1]
I  created a ubuntu ppa for amule-dlp

https://launchpad.net/~lyc256/+archive/amule-dlp/

sudo apt-add-repository ppa:lyc256/amule-dlp
sudo apt-get update
sudo apt-get install anule-dlp

**Comment by persmule** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
    于 2014年01月21日 17:42, lyc256 写道:

```
  I created a ubuntu ppa for amule-alp
  https://launchpad.net/~lyc256/+archive/amule-dlp/
  —
    Reply to this email directly or view it
      on GitHub.

I don't like ubuntu, but it is not concerned. You had better not
name your package as "amule" but keep it as "amule-dlp", for the
amule-dlp project is not the official amule, but a fork from it.
Best Regard
Persmule
```

**Comment by lyc256** [comment]
重命名为amule-dlp，但是与amule冲突
我觉得名字就不那么重要了

2014/1/21 persmule notifications@github.com

**Comment by quzhaojing** [comment]
g++: 错误： ./Scanner.cpp：没有那个文件或目录

**Comment by quzhaojing** [comment]
make 出错了，怎么解决的

**Comment by persmule** [comment]
你肯定没装bison和flex。

**Comment by persmule** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
    于 2014年01月24日 16:00, CharellKing 写道:

```
  g++: 错误： ./Scanner.cpp：没有那个文件或目录
  —
    Reply to this email directly or view
      it on GitHub.

你肯定没装bison和flex。
```

**Comment by persmule** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
    于 2014年01月24日 16:14, persmule 写道:

```
  body p { margin-bottom: 0cm; margin-top: 0pt; } 于 2014年01月24日 16:00, CharellKing 写道:

    g++: 错误： ./Scanner.cpp：没有那个文件或目录
    —
      Reply to this email directly or view

        it on GitHub.

  你肯定没装bison和flex。 
当然不排除autoconf的环境检查有不到位的地方。这里我可能还得慢慢改。
```

**Comment by beautifulzyb** [comment]
为啥我会出现make错误？

: -Pyyip -o IPFilterScanner.cpp ./IPFilterScanner.l;
g++ -DHAVE_CONFIG_H -I. -I..  -D__DEBUG__ -DUSE_WX_EXTENSIONS -DAMULE_DLP -I/usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -DwxUSE_GUI=0 -I./libs -I./include -I/usr/include -D__WEAK_CRYPTO__ -I/usr/include/upnp   -DENABLE_UPNP=1  -g -W -Wall -Wshadow -Wundef -ggdb -fno-inline -fmessage-length=0  -MT libmuleappcore_a-IPFilterScanner.o -MD -MP -MF .deps/libmuleappcore_a-IPFilterScanner.Tpo -c -o libmuleappcore_a-IPFilterScanner.o `test -f 'IPFilterScanner.cpp' || echo './'`IPFilterScanner.cpp
g++: error: ./IPFilterScanner.cpp: 没有那个文件或目录
g++: fatal error: no input files
compilation terminated.
make[3]: **\* [libmuleappcore_a-IPFilterScanner.o] 错误 4
make[3]:正在离开目录 `/home/tink/amule-dlp-master/src'
make[2]: *** [all-recursive] 错误 1
make[2]:正在离开目录`/home/tink/amule-dlp-master/src'
make[1]: **\* [all-recursive] 错误 1
make[1]:正在离开目录 `/home/tink/amule-dlp-master'
make: **\* [all] 错误 2

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


应该是你没装bison和flex。
  在 2015年08月07日 17:22, beautifulzyb 写道:


  为啥我会出现make错误？
    make all-recursive
    make[1]: 正在进入目录 /home/tink/amule-dlp-master'
      Making all in intl
      make[2]: 正在进入目录/home/tink/amule-dlp-master/intl'
    make[2]: 没有什么可以做的为 all'。
      make[2]:正在离开目录/home/tink/amule-dlp-master/intl'
    Making all in po
    make[2]: 正在进入目录 /home/tink/amule-dlp-master/po'
      make[2]: 没有什么可以做的为all'。
    make[2]:正在离开目录 /home/tink/amule-dlp-master/po'
      Making all in docs
      make[2]: 正在进入目录/home/tink/amule-dlp-master/docs'
    Making all in man
    make[3]: 正在进入目录 /home/tink/amule-dlp-master/docs/man'
      make[3]: 没有什么可以做的为all'。
    make[3]:正在离开目录 /home/tink/amule-dlp-master/docs/man'
      make[3]: 正在进入目录/home/tink/amule-dlp-master/docs'
    make[3]: 没有什么可以做的为 all-am'。
      make[3]:正在离开目录/home/tink/amule-dlp-master/docs'
    make[2]:正在离开目录 /home/tink/amule-dlp-master/docs'
      Making all in src
      make[2]: 正在进入目录/home/tink/amule-dlp-master/src'
    Making all in libs
    make[3]: 正在进入目录 /home/tink/amule-dlp-master/src/libs'
      Making all in common
      make[4]: 正在进入目录/home/tink/amule-dlp-master/src/libs/common'
    make[4]: 没有什么可以做的为 all'。
      make[4]:正在离开目录/home/tink/amule-dlp-master/src/libs/common'
    Making all in ec
    make[4]: 正在进入目录 /home/tink/amule-dlp-master/src/libs/ec'
      make all-recursive
      make[5]: 正在进入目录/home/tink/amule-dlp-master/src/libs/ec'
    Making all in cpp
    make[6]: 正在进入目录 /home/tink/amule-dlp-master/src/libs/ec/cpp'
      make all-am
      make[7]: 正在进入目录/home/tink/amule-dlp-master/src/libs/ec/cpp'
    make[7]: 没有什么可以做的为 all-am'。
      make[7]:正在离开目录/home/tink/amule-dlp-master/src/libs/ec/cpp'
    make[6]:正在离开目录 /home/tink/amule-dlp-master/src/libs/ec/cpp'
      make[6]: 正在进入目录/home/tink/amule-dlp-master/src/libs/ec'
    make[6]: 没有什么可以做的为 all-am'。
      make[6]:正在离开目录/home/tink/amule-dlp-master/src/libs/ec'
    make[5]:正在离开目录 /home/tink/amule-dlp-master/src/libs/ec'
      make[4]:正在离开目录/home/tink/amule-dlp-master/src/libs/ec'
    make[4]: 正在进入目录 /home/tink/amule-dlp-master/src/libs'
      make[4]: 没有什么可以做的为all-am'。
    make[4]:正在离开目录 /home/tink/amule-dlp-master/src/libs'
      make[3]:正在离开目录/home/tink/amule-dlp-master/src/libs'
    Making all in utils
    make[3]: 正在进入目录 /home/tink/amule-dlp-master/src/utils'
      make[4]: 正在进入目录/home/tink/amule-dlp-master/src/utils'
    make[4]: 没有什么可以做的为 all-am'。
      make[4]:正在离开目录/home/tink/amule-dlp-master/src/utils'
    make[3]:正在离开目录 /home/tink/amule-dlp-master/src/utils'
      Making all in pixmaps
      make[3]: 正在进入目录/home/tink/amule-dlp-master/src/pixmaps'
    Making all in flags_xpm
    make[4]: 正在进入目录 /home/tink/amule-dlp-master/src/pixmaps/flags_xpm'
      make[4]: 没有什么可以做的为all'。
    make[4]:正在离开目录 /home/tink/amule-dlp-master/src/pixmaps/flags_xpm'
      make[4]: 正在进入目录/home/tink/amule-dlp-master/src/pixmaps'
    make[4]: 没有什么可以做的为 all-am'。
      make[4]:正在离开目录/home/tink/amule-dlp-master/src/pixmaps'
    make[3]:正在离开目录 /home/tink/amule-dlp-master/src/pixmaps'
      Making all in skins
      make[3]: 正在进入目录/home/tink/amule-dlp-master/src/skins'
    make[3]: 没有什么可以做的为 all'。
      make[3]:正在离开目录/home/tink/amule-dlp-master/src/skins'
    make[3]: 正在进入目录 /home/tink/amule-dlp-master/src'
      : -Pyyip -o IPFilterScanner.cpp ./IPFilterScanner.l;
      g++ -DHAVE_CONFIG_H -I. -I.. -D__DEBUG__ -DUSE_WX_EXTENSIONS
      -DAMULE_DLP
      -I/usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-release-2.8
      -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES
      -D__WXGTK__ -DwxUSE_GUI=0 -I./libs -I./include -I/usr/include
      -D__WEAK_CRYPTO__ -I/usr/include/upnp -DENABLE_UPNP=1 -g -W
      -Wall -Wshadow -Wundef -ggdb -fno-inline -fmessage-length=0
      -MT libmuleappcore_a-IPFilterScanner.o -MD -MP -MF
      .deps/libmuleappcore_a-IPFilterScanner.Tpo -c -o
      libmuleappcore_a-IPFilterScanner.otest -f
    'IPFilterScanner.cpp' || echo './'IPFilterScanner.cpp
      g++: error: ./IPFilterScanner.cpp: 没有那个文件或目录
      g++: fatal error: no input files
      compilation terminated.
      make[3]: *** [libmuleappcore_a-IPFilterScanner.o] 错误 4
      make[3]:正在离开目录/home/tink/amule-dlp-master/src'
    make[2]: *** [all-recursive] 错误 1
    make[2]:正在离开目录 /home/tink/amule-dlp-master/src'
      make[1]: *** [all-recursive] 错误 1
      make[1]:正在离开目录/home/tink/amule-dlp-master'
    make: *** [all] 错误 2
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by beautifulzyb** [comment]
我没装flex,但是我装了bison，我后来一生气，在网上看到一个办法，就是在maker后面加-k忽略掉，但是还是不行，装好了flex后，依然行不通呀……

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


当然不可以。IPFilterScanner.cpp是要用flex从IPFilterScanner.l
    自动生成的，你没装flex当然进行不下去了。
  在 2015年08月07日 18:15, beautifulzyb 写道:


  我没装flex,但是我装了bison，我后来一生气，在网上看到一个办法，就是在maker后面加-k忽略掉，不知道这样可以么？
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by beautifulzyb** [comment]
我装了flex之后，还是有问题，主要问题是：
Compiling IPFilterScanner.cpp
IPFilterScanner.cpp:1357:17: warning: ‘void yyunput(int, char_)’ defined but not used [-Wunused-function]
     static void yyunput (int c, register char \* yy_bp )
                 ^
Generating Scanner.cpp
Compiling Scanner.cpp
./Scanner.l:214:5: warning: "YY_STACK_USED" is not defined [-Wundef]
  yy_start_stack_ptr = 0;
     ^
Scanner.cpp: In function ‘int yy_get_next_buffer()’:
Scanner.cpp:1251:39: error: invalid initialization of reference of type ‘size_t& {aka unsigned int&}’ from expression of type ‘int’
    (yy_n_chars), (size_t) num_to_read );
                                       ^
./Scanner.l:28:13: error: in passing argument 2 of ‘void ReadLexBuff(char_, size_t&, size_t)’
 static void ReadLexBuff(char\* pcBuff, size_t& riResult, size_t uMaxSize);
             ^
Scanner.cpp: At global scope:
Scanner.cpp:1817:13: warning: ‘void yy_fatal_error(const char_)’ defined but not used [-Wunused-function]
 static void yy_fatal_error (yyconst char_ msg )
             ^
make[3]: **\* [libmuleappcore_a-Scanner.o] 错误 1
make[2]: **\* [all-recursive] 错误 1
make[1]: **\* [all-recursive] 错误 1
make: **\* [all] 错误 2

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


你用的是最新版么？现在yy_n_chars是size_t类型，不可能有类型转换
  问题。
  在 2015年08月07日 18:29, beautifulzyb 写道:


  我装了flex之后，还是有问题，主要问题是：
    Compiling Scanner.cpp
    ./Scanner.l:214:5: warning: "YY_STACK_USED" is not defined
    [-Wundef]
    yy_start_stack_ptr = 0;
    ^
    Scanner.cpp: In function ‘int yy_get_next_buffer()’:
    Scanner.cpp:1251:39: error: invalid initialization of reference
    of type ‘size_t& {aka unsigned int&}’ from expression of
    type ‘int’
    (yy_n_chars), (size_t) num_to_read );
    ^
    ./Scanner.l:28:13: error: in passing argument 2 of ‘void
    ReadLexBuff(char, size_t&, size_t)’
      static void ReadLexBuff(char pcBuff, size_t&
    riResult, size_t uMaxSize);
    ^
    Scanner.cpp: At global scope:
    Scanner.cpp:1817:13: warning: ‘void yy_fatal_error(const char)’
      defined but not used [-Wunused-function]
      static void yy_fatal_error (yyconst char msg )
    ^
    make[3]: *** [libmuleappcore_a-Scanner.o] 错误 1
    make[2]: *** [all-recursive] 错误 1
    make[1]: *** [all-recursive] 错误 1
    make: *** [all] 错误 2
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by beautifulzyb** [comment]
我就是在这个网站直接下载的呀……   T_T

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


你看一下你生成的Scanner.cpp中yy_n_chars的类型，还有
  flex的版本。
  在 2015年08月07日 18:55, beautifulzyb 写道:


  我就是在这个网站直接下载的呀…… T_T
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by beautifulzyb** [comment]
我下载下来的名称叫：amule-dlp-master.zip
我解压后在~/amule-dlp-master/src文件中的Scanner.cpp中
第213行第一次出现 int yy_n_chars;
第283行显示　static int yy_n_chars;
（以下出现的被我忽略了）
我用flex -V 显示结果
flex 2.5.35

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


你还是用git
  clone吧。src/下根本没有Scanner.cpp，那个文件应该是在编译过程中生成的。
  在 2015年08月07日 19:09, beautifulzyb 写道:


  我下载下来的名称叫：amule-dlp-master.zip
    我解压后在~/amule-dlp-master/src文件中的Scanner.cpp中
    第213行第一次出现 int yy_n_chars;
    第283行显示　static int yy_n_chars;
    （以下出现的被我忽略了）
    我用flex -V 显示结果
    flex 2.5.35
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by beautifulzyb** [comment]
求git clone 详解，刚转linux的小白完全不知道这是什么东西　T_T　　
百度到的答案是用于克隆项目，但是……网址那里怎么写？需要用户名么？

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


上github却不知道git
  clone……真是滑天下之大稽。多用google少用败毒，先变“黑”点再来找我吧，不送！
  在 2015年08月07日 19:21, beautifulzyb 写道:


  求git clone 详解，刚转linux的小白完全不知道这是什么东西　T_T　　
    百度到的答案是用于克隆项目，但是……网址那里怎么写？需要用户名么？
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by beautifulzyb** [comment]
^_^！！
天朝网络上谷歌不容易，所以就百度了。
虽然不知道现在是什么情况，但非常感谢阁下指导。
临别再拜，顿首。

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


上不了google就先用https://search.disconnect.me间
  接上google吧，聊胜于无，远胜败毒。
  在 2015年08月07日 19:31, beautifulzyb 写道:


  ^_^！！
    天朝网络上谷歌不容易，所以就百度了。
    虽然不知道现在是什么情况，但非常感谢阁下指导。
    临别再拜，顿首。
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by BenderBlog** [comment]
/src 没有 Scanner.cpp IPScanner.cpp 
反正我从 git clone 下来的
g++ -DHAVE_CONFIG_H -I. -I..  -D__DEBUG__ -DUSE_WX_EXTENSIONS -DAMULE_DLP -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -DwxUSE_GUI=0 -I./libs -I./include -I/usr/include -D__WEAK_CRYPTO__ -I/usr/include/upnp  -DENABLE_UPNP=1  -g -W -Wall -Wshadow -Wundef -ggdb -fno-inline -fmessage-length=0  -MT libmuleappcore_a-IPFilterScanner.o -MD -MP -MF .deps/libmuleappcore_a-IPFilterScanner.Tpo -c -o libmuleappcore_a-IPFilterScanner.o `test -f 'IPFilterScanner.cpp' || echo './'`IPFilterScanner.cpp
g++: error: ./IPFilterScanner.cpp: 没有那个文件或目录
g++: fatal error: no input files
compilation terminated.
Makefile:1856: recipe for target 'libmuleappcore_a-IPFilterScanner.o' failed
make[3]: **\* [libmuleappcore_a-IPFilterScanner.o] Error 1
g++ -DHAVE_CONFIG_H -I. -I..  -D__DEBUG__ -DUSE_WX_EXTENSIONS -DAMULE_DLP -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -DwxUSE_GUI=0 -I./libs -I./include -I/usr/include -D__WEAK_CRYPTO__ -I/usr/include/upnp  -DENABLE_UPNP=1  -g -W -Wall -Wshadow -Wundef -ggdb -fno-inline -fmessage-length=0  -MT libmuleappcore_a-Scanner.o -MD -MP -MF .deps/libmuleappcore_a-Scanner.Tpo -c -o libmuleappcore_a-Scanner.o `test -f 'Scanner.cpp' || echo './'`Scanner.cpp
g++: error: ./Scanner.cpp: 没有那个文件或目录
g++: fatal error: no input files
compilation terminated.
Makefile:1870: recipe for target 'libmuleappcore_a-Scanner.o' failed
make[3]: **\* [libmuleappcore_a-Scanner.o] Error 1
g++ -DHAVE_CONFIG_H -I. -I..  -D__DEBUG__ -DUSE_WX_EXTENSIONS -DAMULE_DLP -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -DwxUSE_GUI=0 -I./libs -I./include -I/usr/include -D__WEAK_CRYPTO__ -I/usr/include/upnp  -DENABLE_UPNP=1  -g -W -Wall -Wshadow -Wundef -ggdb -fno-inline -fmessage-length=0  -MT libmuleappcore_a-Parser.o -MD -MP -MF .deps/libmuleappcore_a-Parser.Tpo -c -o libmuleappcore_a-Parser.o `test -f 'Parser.cpp' || echo './'`Parser.cpp
mv -f .deps/libmuleappcore_a-Parser.Tpo .deps/libmuleappcore_a-Parser.Po
make[3]: Target 'all-am' not remade because of errors.
make[3]: Leaving directory '/home/superbart/下载/amule-dlp/src'
Makefile:5012: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Target 'all' not remade because of errors.
make[2]: Leaving directory '/home/superbart/下载/amule-dlp/src'
Making all in unittests
make[2]: Entering directory '/home/superbart/下载/amule-dlp/unittests'
make[3]: Entering directory '/home/superbart/下载/amule-dlp/unittests'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/superbart/下载/amule-dlp/unittests'
make[2]: Leaving directory '/home/superbart/下载/amule-dlp/unittests'
make[2]: Entering directory '/home/superbart/下载/amule-dlp'
make[2]: **\* No rule to make target 'amule.xpm', needed by 'all-am'.
make[2]: Target 'all-am' not remade because of errors.
make[2]: Leaving directory '/home/superbart/下载/amule-dlp'
Makefile:630: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/superbart/下载/amule-dlp'
Makefile:524: recipe for target 'all' failed
make: **\* [all] Error 2

以上是make -k的结果

bison 和 flex 已安装

**Comment by cnfanhua** [comment]
系统中已安装amule，请问这两个冲突吗

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


冲突。

在 2016年03月10日 17:53, LI YONG 写道:


  系统中已安装amule，请问这两个冲突吗
```

---

**Comment by persmule** [comment]
```
body p { margin-bottom: 0cm; margin-top: 0pt; } 


确切地说，如果是直接编译安装可以共存，但同时只能使用一个。要是编译成二进制软件包则与原始的amule冲突。

另外ubuntu ppa的二进制包不是我维护的——本人不发行任何二进制目标代码——和打包有关的问题不要问我。

在 2016年03月10日 17:53, LI YONG 写道:


  系统中已安装amule，请问这两个冲突吗
```

---

**Comment by cnfanhua** [comment]
@persmule 多谢。
