### ISSUE TITLE
libwxgtk2.8-dev no longer exists in newer Debian-based distributions

### ISSUE THREAD

**Issue by hosiet** [persmule/amule-dlp#24]
Libwxgtk2.8-dev written in `/debian/control` file no longer exists since Debian 8.

There is libwxgtk3.0-dev, but I'm not sure if API Break in v3.0 breaks amule-dlp.

**Comment by persmule** [comment]
This file on upstream ( https://github.com/amule-project/amule/ ) has
never changed since 2012, so I believe you can ignore it. This amule-dlp
is continuously following the upstream, which can be built out of the
box atop libwxgtk3.0-dev ( https://packages.debian.org/stretch/amule ).

在 2017年03月22日 13:51, Boyuan Yang 写道:
